// <auto-generated />
using System;
using LaLiga.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaLiga.Migrations
{
    [DbContext(typeof(LaLigaContext))]
    partial class LaLigaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("LaLiga.Models.Druzyna", b =>
                {
                    b.Property<int>("id_druzyny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("gole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("nazwa_druzyny")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("punkty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("id_druzyny");

                    b.ToTable("Druzyna");
                });

            modelBuilder.Entity("LaLiga.Models.Mecz", b =>
                {
                    b.Property<int>("id_meczu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_gosci")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_gospodarzy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("termin")
                        .HasColumnType("TEXT");

                    b.HasKey("id_meczu");

                    b.HasIndex("id_gosci");

                    b.HasIndex("id_gospodarzy");

                    b.ToTable("Mecz");
                });

            modelBuilder.Entity("LaLiga.Models.Statystyki", b =>
                {
                    b.Property<int>("id_meczu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("gole_gosci")
                        .HasColumnType("INTEGER");

                    b.Property<int>("gole_gospodarzy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("strzaly_gosci")
                        .HasColumnType("INTEGER");

                    b.Property<int>("strzaly_gospodarzy")
                        .HasColumnType("INTEGER");

                    b.HasKey("id_meczu");

                    b.ToTable("Statystyki");
                });

            modelBuilder.Entity("LaLiga.Models.Strzelec", b =>
                {
                    b.Property<int>("id_druzyny")
                        .HasColumnType("INTEGER");

                    b.Property<int>("numer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_meczu")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("asysty")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("gole")
                        .HasColumnType("INTEGER");

                    b.HasKey("id_druzyny", "numer", "id_meczu");

                    b.HasIndex("id_meczu");

                    b.ToTable("Strzelec");
                });

            modelBuilder.Entity("LaLiga.Models.Uzytkownik", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("data_dolaczenia")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("haslo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rola")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("wiek")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Uzytkownik");
                });

            modelBuilder.Entity("LaLiga.Models.Zawodnik", b =>
                {
                    b.Property<int>("id_druzyny")
                        .HasColumnType("INTEGER");

                    b.Property<int>("numer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("pozycja")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("wartosc_rynkowa")
                        .HasColumnType("TEXT");

                    b.Property<int>("wiek")
                        .HasColumnType("INTEGER");

                    b.HasKey("id_druzyny", "numer");

                    b.ToTable("Zawodnik");
                });

            modelBuilder.Entity("LaLiga.Models.Mecz", b =>
                {
                    b.HasOne("LaLiga.Models.Druzyna", "goscie")
                        .WithMany("meczeNaWyjezdzie")
                        .HasForeignKey("id_gosci")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LaLiga.Models.Druzyna", "gospodarze")
                        .WithMany("meczeUSiebie")
                        .HasForeignKey("id_gospodarzy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("goscie");

                    b.Navigation("gospodarze");
                });

            modelBuilder.Entity("LaLiga.Models.Statystyki", b =>
                {
                    b.HasOne("LaLiga.Models.Mecz", "mecz")
                        .WithOne("stats")
                        .HasForeignKey("LaLiga.Models.Statystyki", "id_meczu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mecz");
                });

            modelBuilder.Entity("LaLiga.Models.Strzelec", b =>
                {
                    b.HasOne("LaLiga.Models.Mecz", "mecz")
                        .WithMany("strzelcy")
                        .HasForeignKey("id_meczu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaLiga.Models.Zawodnik", "zawodnik")
                        .WithMany("strzelcy")
                        .HasForeignKey("id_druzyny", "numer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mecz");

                    b.Navigation("zawodnik");
                });

            modelBuilder.Entity("LaLiga.Models.Zawodnik", b =>
                {
                    b.HasOne("LaLiga.Models.Druzyna", "druzyna")
                        .WithMany("zawodnicy")
                        .HasForeignKey("id_druzyny")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("druzyna");
                });

            modelBuilder.Entity("LaLiga.Models.Druzyna", b =>
                {
                    b.Navigation("meczeNaWyjezdzie");

                    b.Navigation("meczeUSiebie");

                    b.Navigation("zawodnicy");
                });

            modelBuilder.Entity("LaLiga.Models.Mecz", b =>
                {
                    b.Navigation("stats");

                    b.Navigation("strzelcy");
                });

            modelBuilder.Entity("LaLiga.Models.Zawodnik", b =>
                {
                    b.Navigation("strzelcy");
                });
#pragma warning restore 612, 618
        }
    }
}
